### PR TITLE
When bodyCheck does not pass, fail instead of warn

### PR DESCRIPTION
**Pull request by nkapinos**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [x] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Related Tickets & Documents

This PR [adds/removes/fixes/resolves] this [feature/bug/etc]. 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by mtfoley** [comment]
Hi @nkapinos thanks for sending this! I had started a new job in March and haven’t spent much time on here since then.

For what it’s worth in context, this project was originally built to support the projects over at https://github.com/open-sauced/open-sauced, the reasoning behind the title being a failed check while the others are not dealt with there being semantic release automation that runs when a PR is merged. In order for version bumping to work properly, the titles for PRs needed to follow conventional commits.

I’d love to hear more about your use case if you open an issue, and I’d be willing to make changes that add a setting like “bodyCheckOutcome” being set to “warning” (default) or “fail”.

**Comment by nkapinos** [comment]
Hi Matthew!
I've been playing around with this Github Action, and found it useful to be
able to check for Issues linked in a PR.  I'm looking to enforce this
development practice.  Yes, adding a setting so bodyCheckOutcome will fail
and block PR merge (like titleCheck does) is the behavior I'm looking for.

Cheers,
Nate

**Comment by mtfoley** [comment]
@nkapinos sounds good to me.  On second thought, I feel a boolean would be easier to work with here. Would you like to take a crack at the PR for it? If so, I think the scope would be:
- update action.yml to reflect a new input "body-fail", defaulting to false
- update README.md to reflect the new input, including default behavior
- update src/main.ts to check for input and fallback to default value
- update src/main.ts to call the appropriate `core.setFailed` if or `core.warning` method, based on the input. The message can probably stay the same.
- locally run command "npm run all", which should run test suite, linting, and compilation (noted in CONTRIBUTING.md).

If you do decide to work on a PR, make sure to refer to #182.

If you'd rather not, I'm happy to do it :-)

**Comment by mtfoley** [comment]
Closing this since #193 landed.

**Pull request closed without merging**
